using System;
using Microsoft.VisualStudio.Shell;

namespace Microsoft.VisualStudioUI.VSWin
{
    // This class is copied from src/env/shell/UIInternal/Packages/InfoBadge/Common/InfoBadgeColors.cs
    // TODO: Make it public in VS so no copy is needed here
    internal class InfoBadgeColors
    {
        #region Autogenerated resource keys
        // These resource keys are generated by Visual Studio Extension Color Editor, and should be replaced when new colors are added to this category.
        public static readonly Guid Category = new Guid("63f9718c-889b-4814-a3b4-6e81d14f1156");

        private static ThemeResourceKey _SystemBackgroundColorKey;
        private static ThemeResourceKey _SystemBackgroundBrushKey;
        public static ThemeResourceKey SystemBackgroundColorKey { get { return _SystemBackgroundColorKey ?? (_SystemBackgroundColorKey = new ThemeResourceKey(Category, "Background", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SystemBackgroundBrushKey { get { return _SystemBackgroundBrushKey ?? (_SystemBackgroundBrushKey = new ThemeResourceKey(Category, "Background", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _BackgroundDisabledColorKey;
        private static ThemeResourceKey _BackgroundDisabledBrushKey;
        public static ThemeResourceKey BackgroundDisabledColorKey { get { return _BackgroundDisabledColorKey ?? (_BackgroundDisabledColorKey = new ThemeResourceKey(Category, "BackgroundDisabled", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey BackgroundDisabledBrushKey { get { return _BackgroundDisabledBrushKey ?? (_BackgroundDisabledBrushKey = new ThemeResourceKey(Category, "BackgroundDisabled", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _BackgroundFocusedColorKey;
        private static ThemeResourceKey _BackgroundFocusedBrushKey;
        public static ThemeResourceKey BackgroundFocusedColorKey { get { return _BackgroundFocusedColorKey ?? (_BackgroundFocusedColorKey = new ThemeResourceKey(Category, "BackgroundFocused", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey BackgroundFocusedBrushKey { get { return _BackgroundFocusedBrushKey ?? (_BackgroundFocusedBrushKey = new ThemeResourceKey(Category, "BackgroundFocused", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _BackgroundHoverColorKey;
        private static ThemeResourceKey _BackgroundHoverBrushKey;
        public static ThemeResourceKey BackgroundHoverColorKey { get { return _BackgroundHoverColorKey ?? (_BackgroundHoverColorKey = new ThemeResourceKey(Category, "BackgroundHover", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey BackgroundHoverBrushKey { get { return _BackgroundHoverBrushKey ?? (_BackgroundHoverBrushKey = new ThemeResourceKey(Category, "BackgroundHover", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _BackgroundPressedColorKey;
        private static ThemeResourceKey _BackgroundPressedBrushKey;
        public static ThemeResourceKey BackgroundPressedColorKey { get { return _BackgroundPressedColorKey ?? (_BackgroundPressedColorKey = new ThemeResourceKey(Category, "BackgroundPressed", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey BackgroundPressedBrushKey { get { return _BackgroundPressedBrushKey ?? (_BackgroundPressedBrushKey = new ThemeResourceKey(Category, "BackgroundPressed", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _TextColorKey;
        private static ThemeResourceKey _TextBrushKey;
        public static ThemeResourceKey TextColorKey { get { return _TextColorKey ?? (_TextColorKey = new ThemeResourceKey(Category, "Text", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey TextBrushKey { get { return _TextBrushKey ?? (_TextBrushKey = new ThemeResourceKey(Category, "Text", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _TextDisabledColorKey;
        private static ThemeResourceKey _TextDisabledBrushKey;
        public static ThemeResourceKey TextDisabledColorKey { get { return _TextDisabledColorKey ?? (_TextDisabledColorKey = new ThemeResourceKey(Category, "TextDisabled", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey TextDisabledBrushKey { get { return _TextDisabledBrushKey ?? (_TextDisabledBrushKey = new ThemeResourceKey(Category, "TextDisabled", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _TextFocusedColorKey;
        private static ThemeResourceKey _TextFocusedBrushKey;
        public static ThemeResourceKey TextFocusedColorKey { get { return _TextFocusedColorKey ?? (_TextFocusedColorKey = new ThemeResourceKey(Category, "TextFocused", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey TextFocusedBrushKey { get { return _TextFocusedBrushKey ?? (_TextFocusedBrushKey = new ThemeResourceKey(Category, "TextFocused", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _TextHoverColorKey;
        private static ThemeResourceKey _TextHoverBrushKey;
        public static ThemeResourceKey TextHoverColorKey { get { return _TextHoverColorKey ?? (_TextHoverColorKey = new ThemeResourceKey(Category, "TextHover", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey TextHoverBrushKey { get { return _TextHoverBrushKey ?? (_TextHoverBrushKey = new ThemeResourceKey(Category, "TextHover", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _TextPressedColorKey;
        private static ThemeResourceKey _TextPressedBrushKey;
        public static ThemeResourceKey TextPressedColorKey { get { return _TextPressedColorKey ?? (_TextPressedColorKey = new ThemeResourceKey(Category, "TextPressed", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey TextPressedBrushKey { get { return _TextPressedBrushKey ?? (_TextPressedBrushKey = new ThemeResourceKey(Category, "TextPressed", ThemeResourceKeyType.BackgroundBrush)); } }
        #endregion
    }
}
